export const firstNameError: string = 'First name should contain at least 2 characters'
export const lastNameError: string = 'Last name should contain at least 2 characters'
export const emailError: string = 'Enter a valid email'
export const passwordError: string = 'At least 8 characters with numbers and an uppercase letter'
export const userNotFoundError: string = 'User not found. Sign In to create a new account.'
export const incorrectPasswordError: string = 'Incorrect password'
export const networkError: string = 'A network error was encountered!'
